name: Update release version.
on:
  release:
    types: [published]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --depth=1 origin +refs/heads/master:refs/remotes/origin/master
      - run: git fetch origin +refs/tags/*:refs/tags/*
      - name: Bumpversion release version.
        uses: tj-actions/bumpversion@v2
        id: bumpversion
        with:
          paths: |
            README.md
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git stash
          git checkout -B upgrade-version
          git stash pop
          git add README.md
          git commit -m "Updraded from ${{ steps.bumpversion.outputs.old_version }} -> ${{ steps.bumpversion.outputs.new_version }}"
          git checkout master
          git merge upgrade-version
          git push
